"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](color_bg1)\
$os\
$username\
[](bg:color_bg2 fg:color_bg1)\
$directory\
[](fg:color_bg2 bg:color_bg3)\
$git_branch\
$git_status\
[](fg:color_bg3 bg:color_bg4)\
$c\
$cpp\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:color_bg4 bg:color_bg5)\
$docker_context\
$conda\
$pixi\
[](fg:color_bg5 bg:color_bg6)\
$time\
[ ](fg:color_bg6)\
$line_break$character"""

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_fg = '#ffffff'

#color_bg1 = '#101010'
#color_bg2 = '#202020'
#color_bg3 = '#303030'
#color_bg4 = '#404040'
#color_bg5 = '#505050'
#color_bg6 = '#606060'

color_bg1 = '#17191c'
color_bg2 = '#202427'
color_bg3 = '#2a2e32'
color_bg4 = '#33383d'
color_bg5 = '#3c4248'
color_bg6 = '#464d53'

color_purple = '#b16286'
color_green = '#00ff00'
color_red = '#ff0000'


[os]
disabled = false
style = "bg:color_bg1 fg:color_fg"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[username]
show_always = true
style_user = "bg:color_bg1 fg:color_fg"
style_root = "bg:color_bg1 fg:color_fg"
format = '[ $user ]($style)'

[directory]
style = "fg:color_fg bg:color_bg2"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:color_bg3"
format = '[[ $symbol $branch ](fg:color_fg bg:color_bg3)]($style)'

[git_status]
style = "bg:color_bg3"
format = '[[($all_status$ahead_behind )](fg:color_fg bg:color_bg3)]($style)'

[nodejs]
symbol = ""
style = "bg:color_bg4"
format = '[[ $symbol( $version) ](fg:color_fg bg:color_bg4)]($style)'

[c]
symbol = " "
style = "bg:color_bg4"
format = '[[ $symbol( $version) ](fg:color_fg bg:color_bg4)]($style)'

[cpp]
symbol = " "
style = "bg:color_bg4"
format = '[[ $symbol( $version) ](fg:color_fg bg:color_bg4)]($style)'

[rust]
symbol = ""
style = "bg:color_bg4"
format = '[[ $symbol( $version) ](fg:color_fg bg:color_bg4)]($style)'

[golang]
symbol = ""
style = "bg:color_bg4"
format = '[[ $symbol( $version) ](fg:color_fg bg:color_bg4)]($style)'

[php]
symbol = ""
style = "bg:color_bg4"
format = '[[ $symbol( $version) ](fg:color_fg bg:color_bg4)]($style)'

[java]
symbol = ""
style = "bg:color_bg4"
format = '[[ $symbol( $version) ](fg:color_fg bg:color_bg4)]($style)'

[kotlin]
symbol = ""
style = "bg:color_bg4"
format = '[[ $symbol( $version) ](fg:color_fg bg:color_bg4)]($style)'

[haskell]
symbol = ""
style = "bg:color_bg4"
format = '[[ $symbol( $version) ](fg:color_fg bg:color_bg4)]($style)'

[python]
symbol = ""
style = "bg:color_bg4"
format = '[[ $symbol( $version) ](fg:color_fg bg:color_bg4)]($style)'

[docker_context]
symbol = ""
style = "bg:color_bg5"
format = '[[ $symbol( $context) ](fg:#83a598 bg:color_bg5)]($style)'

[conda]
style = "bg:color_bg5"
format = '[[ $symbol( $environment) ](fg:#83a598 bg:color_bg5)]($style)'

[pixi]
style = "bg:color_bg5"
format = '[[ $symbol( $version)( $environment) ](fg:color_fg bg:color_bg5)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:color_bg6"
format = '[[ $time ](fg:color_fg bg:color_bg6)]($style)'

[line_break]
disabled = false

[character]
disabled = true
success_symbol = '[](bold fg:color_green)'
error_symbol = '[](bold fg:color_red)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_bg2)'
